### ISSUE TITLE
Starting...

### ISSUE THREAD

**Issue by MrGoogol** [jlennox/HeartRate#2] opened 2017-07-21 18:59 UTC
I am using Windows10 and I looked through the sln but was not able to figure out why:

Connection was established with the PolarH10. Running heartrate_1.2\HeartRate.exe opens window that just says "Starting..."

how does it work; will it write a csv file or something? thank you!

**Comment by jlennox** [comment] 2017-07-21 19:27
Hmm, it shows "Starting..." while waiting for the first signal to come from the device.

It does not log to a file, it only displays directly to the screen.

What does the tooltip say when you mouse over the notification area icon the program adds? This should contain more information.

**Comment by mike121** [comment] 2017-07-31 23:32
Hello, I tried many more times but was not able to get it to work. When I build the solution in VS it does the same thing so it's something on my end. Was there a way to send "connect" command to PolarH10 sensor? (With my other Bluetooth device I have to make it go "ready to pair another device" mode with a button but PolarH10 has no buttons)

**Comment by jlennox** [comment] 2017-08-01 00:03
You should pair it through the usual Windows bluetooth configuration then launch the program. If that's done already, let me know and I'll try and make a debug build for you.

If you run it with the debugger attached using a debug build in visual studio, the debug pane inside VS will display extra details.

**Comment by MM121z** [comment] 2017-09-25 14:26
Ok, I am committed to re-installing windows to get this to work. Will try again and let you know. Thank you.

**Comment by jlennox** [comment] 2017-09-25 17:32
That's pretty drastic! If you want, we could setup a screen sharing session so I can better remote diagnose this.

Keep in mind, this was a small several hour project of mine to fill a single use case, so it not working for you is very possibly my fault and not yours :)

**Comment by aoyangnigel** [comment] 2017-11-13 09:03
I am also having this issue. I'm using Windows 10 with Polar H7. I already paired and connected the device to windows but whenever I run the program all it says is "Starting..."

**Comment by adadurov** [comment] 2018-03-20 10:47
Please check this: https://github.com/jlennox/HeartRate/pull/4
May be the root cause after all.

**Comment by jlennox** [comment] 2018-03-20 14:33
Thank you so much for the pull request @adadurov 

@aoyangnigel and @MrGoogol If still interested in the project, could you guys try again with the instructions in the freshly updated `readme.md`?

**Comment by adadurov** [comment] 2018-03-20 20:41
@jlennox, not at all -- glad to help.
With the workaround, I can run both your app and mine for long time and capture hundreds of intervals without an issue.

**Closed** 2020-09-02 15:50 UTC
